apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: api-key-policy
spec:
  apiKey:
    suppliedIn:
      header:
      - "X-header-name"
      - "apikey"
      - "some-other-header"
      query:
      - "queryName"
    rejectCodes: # optional
      notSupplied: 401
      noMatch: 403
    clientSecret: api-key-client-secret-1
